import Foundation

enum AgentStrings {
    static let title = LocalizedStringResource("agent.title", table: "Agent")
    static let subtitle = LocalizedStringResource("agent.subtitle", table: "Agent")
    static let hero = LocalizedStringResource("agent.hero", table: "Agent")
    static let heroDetail = LocalizedStringResource("agent.hero.detail", table: "Agent")
    static let prompt = LocalizedStringResource("agent.prompt", table: "Agent")
    static let send = LocalizedStringResource("agent.send", table: "Agent")
    static let signIn = LocalizedStringResource("agent.signIn", table: "Agent")
    static let runningCloud = LocalizedStringResource("agent.runningCloud", table: "Agent")
    static let plan = LocalizedStringResource("agent.plan", table: "Agent")
    static let activity = LocalizedStringResource("agent.activity", table: "Agent")
    static let files = LocalizedStringResource("agent.files", table: "Agent")
    static let result = LocalizedStringResource("agent.result", table: "Agent")
    static let credits = LocalizedStringResource("agent.credits", table: "Agent")
    static let creditsRemaining = LocalizedStringResource("agent.credits.remaining", table: "Agent")
    static let creditsUsed = LocalizedStringResource("agent.credits.used", table: "Agent")
    static let download = LocalizedStringResource("agent.download", table: "Agent")
    static let share = LocalizedStringResource("agent.share", table: "Agent")
    static let newMission = LocalizedStringResource("agent.newMission", table: "Agent")
    static let dismissError = LocalizedStringResource("agent.dismissError", table: "Agent")
    static let queued = LocalizedStringResource("agent.phase.queued", table: "Agent")
    static let running = LocalizedStringResource("agent.phase.running", table: "Agent")
    static let done = LocalizedStringResource("agent.phase.done", table: "Agent")
    static let failed = LocalizedStringResource("agent.phase.failed", table: "Agent")
    static let pending = LocalizedStringResource("agent.step.pending", table: "Agent")
    static let openSidebar = LocalizedStringResource("agent.openSidebar", table: "Agent")
    static let account = LocalizedStringResource("agent.account", table: "Agent")
}
