/* ============================================================================
   Firas AI — Local Knowledge Base compiler
   ----------------------------------------------------------------------------
   Walks the subject folders (math/ science/ arabic/ quran/ …) and flattens every
   topic file into ONE portable artifact both runtimes import:

     knowledge/compiled.mjs   →  `export default [ {id,subject,topic,title,chunks[]}, … ]`
                                  (server.mjs and the Netlify edge function import this)
     knowledge/compiled.json  →  same data, for tooling / inspection
     knowledge/index.json     →  human manifest: subjects → topics → entry counts

   HOW TO ADD KNOWLEDGE (scales to thousands of files):
     1. Drop a JSON file in a subject folder, e.g. knowledge/math/vectors.json:
        { "subject":"math", "topic":"vectors", "title":"المتجهات — Vectors",
          "entries":[ { "q":"…", "k":["…"], "a":"…" }, … ] }
        q = title/question · k = keywords (boost retrieval) · a = the fact/answer.
        Keep each entry short (≈ one idea, < 700 chars) so it stays one chunk.
     2. Run:  node knowledge/build.mjs
     3. Restart the server (or redeploy). The new knowledge is live — no code change.

   Retrieval is lexical (token overlap) and cached in memory, so it never touches
   latency; only genuinely relevant passages are injected as hidden grounding.
   ========================================================================== */
import { readdirSync, statSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));
// Subject folders scanned, in a stable order. Add a folder name here to include it.
const SUBJECT_DIRS = ["math", "science", "arabic", "quran", "cs", "english"];

function listJsonFiles(dir) {
  let out = [];
  let entries;
  try { entries = readdirSync(dir); } catch { return out; }
  for (const name of entries) {
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) out = out.concat(listJsonFiles(p));
    else if (/\.json$/i.test(name)) out.push(p);
  }
  return out.sort();
}

const books = [];
const manifest = {};
let fileCount = 0, entryCount = 0, chunkCount = 0;
const errors = [];

for (const sub of SUBJECT_DIRS) {
  const dir = join(ROOT, sub);
  for (const file of listJsonFiles(dir)) {
    const rel = relative(ROOT, file).replace(/\\/g, "/");
    let data;
    try { data = JSON.parse(readFileSync(file, "utf8")); }
    catch (e) { errors.push(rel + ": invalid JSON — " + e.message); continue; }
    const subject = String(data.subject || sub).trim();
    const topic = String(data.topic || rel.split("/").pop().replace(/\.json$/i, "")).trim();
    const title = String(data.title || topic).trim();
    const entries = Array.isArray(data.entries) ? data.entries : [];
    if (!entries.length) { errors.push(rel + ": no entries"); continue; }

    const chunks = [];
    for (const e of entries) {
      if (!e) continue;
      // Accept BOTH the simple seed shape { q, k, a } and the bilingual fleet shape
      // { q_ar, q_en, keywords, a_ar, a_en }. Both languages go into one chunk so a
      // query in Arabic OR English surfaces the passage and the model can use either.
      const q = String(e.q || [e.q_ar, e.q_en].filter(Boolean).join(" / ") || "").trim();
      const kwArr = e.k || e.keywords || [];
      const k = Array.isArray(kwArr) ? kwArr.filter(Boolean).map(String).join(" ") : "";
      let a = (typeof e.a === "string" ? e.a : "").trim();
      if (!a) a = [e.a_ar, e.a_en].filter((x) => typeof x === "string" && x.trim()).join("  ▸  ").trim();
      if (!a) { errors.push(rel + ": entry missing answer text"); continue; }
      // chunk = question | keywords | answer — so a query matching the heading or a
      // keyword still surfaces the passage, not only the body text.
      let chunk = [q, k, a].filter(Boolean).join(" | ").replace(/\s+/g, " ").trim();
      if (chunk.length > 1600) chunk = chunk.slice(0, 1600) + "…";
      if (chunk.length > 25) { chunks.push(chunk); entryCount++; }
    }
    if (!chunks.length) { errors.push(rel + ": produced no usable chunks"); continue; }

    books.push({ id: subject + "/" + topic, subject, topic, title, chunks });
    chunkCount += chunks.length;
    fileCount++;
    (manifest[subject] ||= {});
    manifest[subject][topic] = { title, entries: chunks.length };
  }
}

const compiledJson = JSON.stringify(books);
const banner = "// AUTO-GENERATED by knowledge/build.mjs — do NOT edit by hand.\n" +
  "// Edit the topic JSON files under knowledge/<subject>/ then run: node knowledge/build.mjs\n";
writeFileSync(join(ROOT, "compiled.mjs"), banner + "export default " + compiledJson + ";\n");
writeFileSync(join(ROOT, "compiled.json"), compiledJson + "\n");
writeFileSync(join(ROOT, "index.json"), JSON.stringify({
  generatedFrom: SUBJECT_DIRS,
  files: fileCount, topics: chunkCount ? Object.values(manifest).reduce((n, t) => n + Object.keys(t).length, 0) : 0,
  entries: entryCount, chunks: chunkCount, subjects: manifest,
}, null, 2) + "\n");

console.log("[knowledge] compiled " + books.length + " topic-books · " + chunkCount + " chunks from " + fileCount + " files");
for (const s of Object.keys(manifest)) {
  console.log("  " + s + ": " + Object.keys(manifest[s]).length + " topics, " +
    Object.values(manifest[s]).reduce((n, t) => n + t.entries, 0) + " entries");
}
if (errors.length) { console.warn("[knowledge] " + errors.length + " warning(s):"); errors.forEach((e) => console.warn("  ⚠ " + e)); }
