import Foundation

/// The brief Firas is given when the reader asks for a document.
///
/// The owner described the pipeline as three engineers: one designs the file, one places the text,
/// one converts it. The second and third are now code — `DocumentHTML` composes the page and
/// `DocumentPrinter` prints it — which leaves the first, and the first is the model. This is how it
/// is asked.
///
/// The distinction that matters, and the reason this file exists at all: the old file guidance
/// asked for *content in a format*. A reader who says «اصنع لي ملف PDF بيه ١٠ معادلات» is not asking
/// for ten equations in a PDF-shaped container; they are asking for a **paper**. Those are different
/// requests and they produce visibly different documents.
extension PromptCatalog {

    /// Appended as its own system message on a document turn.
    ///
    /// A separate message rather than a paragraph on the end of the main prompt, for the same
    /// reason plan mode needed one: an instruction that arrives as the last line of a four-thousand
    /// token brief is read as a footnote to it.
    static func documentBrief(lang: String, format: String, described: String) -> String {
        var out = base
        out += "\n\nFORMAT: " + format.uppercased() + "."
        let wanted = described.trimmingCharacters(in: .whitespacesAndNewlines)
        if !wanted.isEmpty {
            /* WHAT THE READER ASKED FOR ABOUT THE LOOK, carried through verbatim. «ممكن اوصف اله
               شكل الملف الي اريده مميزاته» — if they described it, that description outranks every
               default below, and paraphrasing it into a summary is how a described document comes
               back generic. */
            out += "\n\nTHE READER DESCRIBED WHAT THEY WANT. Follow it before any default above:\n"
            out += String(wanted.prefix(1_200))
        }
        out += lang == "en" ? "\n\nWrite in English." : "\n\nاكتب بالعربية."
        return out
    }

    /// The one place the five template names are described to the model. They are the same five
    /// `DocTemplate` knows, and the model naming one is what puts the ministry masthead on an exam
    /// paper instead of leaving the resolver to guess from the request text.
    private static let base = ##"""
    You are producing a DOCUMENT — a designed, finished paper that someone will print, hand in, or
    file. Not an outline of one, not a chat answer about one, and not a summary of what such a
    document would contain. If the reader asked for ten problems with solutions, the document
    contains ten problems and their full solutions.

    OPEN WITH ONE FENCED METADATA BLOCK, exactly this and nothing else before it:
    ```firas-file
    {"filename":"a short name, no extension","title":"the document's real title","subtitle":"one line, or empty","template":"ministry|academic|corporate|magazine|plain"}
    ```
    Then the document itself, in markdown, immediately after the closing fence.

    CHOOSING THE TEMPLATE — pick the one the document IS, not the one that sounds impressive:
    * ministry — an exam, a quiz, a worksheet, a question bank, a problem set. An official paper.
    * academic — a research paper, a thesis chapter, anything with sections and citations.
    * corporate — a business report, a plan, a feasibility study, anything with figures and tables.
    * magazine — an article, an editorial, a newsletter.
    * plain — a letter, a memo, notes, or anything the four above would overdress.

    HOW TO WRITE IT
    * Structure it with `##` and `###`. A document with no headings is a wall, and the page builds
      its contents list from these.
    * Use a markdown table wherever the content is genuinely tabular — comparisons, data, marks,
      schedules. The page typesets a real table that repeats its header across a page break.
    * Mathematics goes in LaTeX: `$…$` inside a sentence, `$$…$$` on its own line. It is TYPESET on
      the page by KaTeX, so write it properly — \frac, \int, \sqrt, \sum, subscripts, matrices,
      \ce{} for chemistry. Never write an equation as plain characters and never approximate one;
      the page can set anything KaTeX can set.
    * Code goes in a fenced block with its language. The page prints the whole listing.
    * Write the content, in full. No placeholders, no "[add detail here]", no promising a section
      and leaving it a heading.

    WHAT NOT TO DO
    * Do not write the HTML or the CSS. The page is built for you, with a professional template.
    * Do not add a cover page, a header, a footer, a page number or a table of contents in markdown.
      The template draws all of those, and a second set drawn in the text is what makes a document
      look homemade.
    * Do not sign it, credit yourself, or add "generated by". This is the reader's document.
    """##
}
